### ISSUE TITLE
Add opencontainer labels on the Docker images

### ISSUE THREAD

**Issue by onedr0p** [letsblockit/letsblockit#417] opened 2023-05-05 22:42 UTC
### Description

Hi 👋🏼 it would be awesome if the container image had opencontainers labels. https://github.com/opencontainers/image-spec/blob/main/annotations.md

Some of these labels can be set statically within the Dockerfile and others need to be set during build time.

Docker inspect shows no labels on the image:

```json
[
    {
        "Id": "sha256:e18a364162dd6b7b76b6a494d0bf88c1553fd9bd0e2311c6a29e77dc6a1e3f63",
        "RepoTags": [
            "ghcr.io/letsblockit/server:v0.35.1"
        ],
        "RepoDigests": [
            "ghcr.io/letsblockit/server@sha256:e18a364162dd6b7b76b6a494d0bf88c1553fd9bd0e2311c6a29e77dc6a1e3f63"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "0001-01-01T00:00:00Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8765/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "LETSBLOCKIT_ADDRESS=:8765",
                "PATH=/bin"
            ],
            "Cmd": [
                "/bin/server"
            ],
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 48228711,
        "VirtualSize": 48228711,
        "GraphDriver": {
            "Data": null,
            "Name": "stargz"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:7ae621d392895cbce3bd0e2a315eba50a681bcfb1113b18ac16b57207d8bb4cd",
                "sha256:6dabf11f3bd6528bf4c52db34e7f0ec010de52e7830e06a89da52aa139608512",
                "sha256:53d5ef5bd18098d7bad4bdd180165887fc0f36072802e9d37a3a0c1601a0bab3",
                "sha256:88a0329b88bd90d6d260108be210267caf5ed3657f4690bde64b044155e67179",
                "sha256:66f10b304a43af317d141e19cad4a8fed5fac241e073464a3d1f8149cad11af3",
                "sha256:8f33a9bcf0e795e34afe001b2757334c54322421e29eb82b8b740b542ea38be8",
                "sha256:b98ce3cb3fe6a2aba8944e7fbe23dc899139d191236f9140f0c5695df61cab9c",
                "sha256:78131e22bf281b7c25df52d0d39836ab00f97fc8c4d2a9cb905dad76afeb6012",
                "sha256:f7e6b21e6f93f9d1ce3f8446e113190d31204515840ee784adf64bda06630ef9",
                "sha256:9157c1539f8111ab68315b479eaa4779a4987e5976dc29382da704818fba8bd7",
                "sha256:ed07868de0fadefba4ead53127676d51e911b3da6a1c77c091e74c7dfae34e67",
                "sha256:7091139d938445373dc2c3f4a698f15691af376899199474ba4c7859b0eb8ebc",
                "sha256:0b28b1cb4db61a2382911694165ebecc605350f2cec831d965cdd8acc9526179"
            ]
        },
        "Metadata": {
            "LastTagTime": "2023-05-05T22:41:43.488094545Z"
        }
    }
]
```

Here's an example of an image I build with opencontainers labels:

```json
"Labels": {
    "org.opencontainers.image.authors": "Devin Buhl <devin.kray@gmail.com>, Bernd Schorgers <me@bjw-s.dev>",
    "org.opencontainers.image.build.url": "https://github.com/onedr0p/containers/actions/runs/2812729352",
    "org.opencontainers.image.created": "2022-08-07 13:07:38+00:00",
    "org.opencontainers.image.documentation": "https://github.com/onedr0p/containers/apps/radarr/README.md",
    "org.opencontainers.image.revision": "2304020a942b6b4f4337df8d83ea8c45afae4cdc",
    "org.opencontainers.image.source": "https://github.com/Radarr/Radarr",
    "org.opencontainers.image.title": "radarr (master)",
    "org.opencontainers.image.url": "https://github.com/onedr0p/containers/apps/radarr",
    "org.opencontainers.image.version": "4.1.0.6175"
},

**Comment by onedr0p** [comment] 2023-05-05 22:43
I looked at the build process but I am a bit unfamiliar with the nix workflow you all have for building and pushing image.

**Comment by xvello** [comment] 2023-05-07 12:19
Hello @onedr0p, thanks for opening this issue! I am not aware of the use-cases for this label, could you please give me examples?

Adding static labels should be trivial, by editing `flake.nix`. I think we'll need to add them to the `config` section, like [described in the nixos docs](https://nixos.org/manual/nixpkgs/stable/#ssec-pkgs-dockerTools-buildLayeredImage).

The dynamic ones (`created`, `revision` and `version`) would be harder to add, because Nix designed for reproductible outputs. Do you know of use cases for these ones?

**Comment by onedr0p** [comment] 2023-05-07 12:34
The dynamic ones are probably not needed. However the static ones would be nice, in my usecase I deploy Let's Block It at home and my configuration is tracked in Git. Any time an update comes in I get a PR created by renovatebot like this:

https://github.com/onedr0p/home-ops/pull/5268

Having the name and URL as labels would allow for the release notes to be embedded into the PR like this:

https://github.com/onedr0p/home-ops/pull/5269

Thanks for hearing me out!

**Comment by xvello** [comment] 2023-05-07 16:03
Cool! I'll look into it next week.

**Comment by xvello** [comment] 2023-05-09 18:52
Heya @onedr0p, https://github.com/letsblockit/letsblockit/pull/419 should hopefully address this issue.

Could you please give a look at https://github.com/letsblockit/letsblockit/pkgs/container/server-dev/91928792?tag=f3432e7 and tell me whether the annotations (at the bottom of the page) look OK to you? When triggered on a release, the `version` annotation will hold the tag name.

**Comment by onedr0p** [comment] 2023-05-09 19:01
@xvello excellent! I think that looks fine from here. 👏🏼

**Comment by xvello** [comment] 2023-05-09 19:14
Cool! I'll close this issue then, but don't hesitate to re-open if adjustments are needed.

**Closed by xvello** 2023-05-09 19:14 UTC
Labels: packaging, self-hosting

**Comment by onedr0p** [comment] 2023-05-11 12:48
Superb, this saves me a few clicks on figuring out what changed before I merge this PR to apply it to my Kubernetes cluster :)

https://github.com/onedr0p/home-ops/pull/5291
