### ISSUE TITLE
youtube-shorts: not matching since Feb 28th?

### ISSUE THREAD

**Issue by Kenneth-Rosenstroem** [letsblockit/letsblockit#370] opened 2023-02-28 18:39 UTC
### What filter does this issue target?

https://letsblock.it/filters/youtube-shorts

### What changes should be made?

Screenshot: https://imagetwist.com/897oztbfrt5l/screenshot1.jpeg

### Additional notes

Maybe you could make an update for the new changes.

**Comment by BPower0036** [comment] 2023-02-28 19:18
Didn't notice anything different on my youtube. Maybe I have to wait a couple of days before I get the change and can update the filters.

**Comment by xvello** [comment] 2023-02-28 20:53
Hello @Kenneth-Rosenstroem, thanks for opening an issue!

As @BPower0036, I am currently unable to reproduce this issue. This is not unheard of though, as Google likes to rollout changes progressively across a whole week, so the people in the first rollout batches will get regressions first.

But I'd like to confirm that it's not a browser issue first, could you please:

  - state your browser and uBlockOrigin versions

  - try manually [refreshing your list](https://letsblock.it/help/refresh-list), and tell me how many rules are marked as used, as shown in this screenshot:
<img width="434" alt="Screenshot 2023-02-28 at 21 50 32" src="https://user-images.githubusercontent.com/6241083/221976646-c426efea-2fa8-4286-9ebe-2ed230a22c5a.png">

  - confirm that uBlockOrigin is not disabled for that website, and that cosmetic filtering (the eye icon) is not disabled either. Like in the screenshot below, click on `More` of the icon row does not show:
 
<img width="265" alt="Screenshot 2023-02-28 at 21 52 04" src="https://user-images.githubusercontent.com/6241083/221977006-e7804e4f-5b02-4ce5-a037-2469d53f63a5.png">

**Comment by Kenneth-Rosenstroem** [comment] 2023-02-28 21:22
Just updated Firefox to 110.0.1 and it fixed the problem.
I already tried the refresh of subscriptions. The latest version of Ublock 1.47.2
Thanks for your time and help.

**Comment by xvello** [comment] 2023-03-01 12:30
Youtube interface changes usually trigger a spike of activity on https://www.reddit.com/r/ublockorigin/ but I don't see any post on that issue for now.

I'll pin that issue for visibility and wait a week for other reports to confirm this is not a browser issue.

**Comment by krystian3w** [comment] 2023-03-06 07:30
As demo you can try share html of one row with these shorts.

Maybe on pastebin.com?

**Comment by xvello** [comment] 2023-03-08 22:24
Closing as there has not been any other report of such an issue. Happy to re-open if that were to happen.

**Closed by xvello** 2023-03-08 22:24 UTC
Labels: filter-data
