### ISSUE TITLE
Hide Youtube videos you already watched

### ISSUE THREAD

**Issue by 3DWORX-SA** [letsblockit/letsblockit#304] opened 2022-11-12 15:32 UTC
### What filter does this issue target?

https://letsblock.it/filters/youtube-watched

### What changes should be made?

When "Hide watched videos on the subscriptions and channel pages" is NOT checked, watched videos on a channel's "videos" page are hidden.

**Comment by xvello** [comment] 2022-11-13 08:47
Thanks for the report @3DWORX-SA !

My guess is that the rule for "Hide watched videos on the homepage " is also matching channel pages, we'll need to make these more specific. I'll look into thisa Tuesday.

**Comment by 3DWORX-SA** [comment] 2022-11-13 18:20
Thank you for your effort! I hope that my constructive feedback is helpful.

Regards

**Comment by xvello** [comment] 2023-01-08 18:09
Heya, thanks for your patience. This is fixed in today's deploy.

The issue is that the homepage rule was not specific enough, and matching the channel page too. This is why I could not reproduce this issue.

**Closed** 2023-01-08 18:20 UTC
Labels: bug, filter-data

**Comment by 3DWORX-SA** [comment] 2023-01-09 06:03
Hey, thanks Xavier! This has made the YouTube experience so much better. I have even found videos on some of my favourite channels that I'd missed. FYI, I check the following settings:
- Only hide fully-watched videos (keep partially-watched videos)
- Hide watched videos on the homepage

I prefer it unchecked for the subscriptions and channel pages, so that I can look through and find some videos to watch again or send to other people.

Thanks for your effort - very much appreciated!
