### ISSUE TITLE
Hide Youtube #shorts - iPad

### ISSUE THREAD

**Issue by Melonking906** [letsblockit/letsblockit#307] opened 2022-11-13 21:34 UTC
### What filter does this issue target?

Hide Youtube #shorts

### What changes should be made?

For some reason the shorts filter in entirely ineffective on iPads looking at YouTube via Safari with the AdGuard app. Shorts show up in subscriptions and the shorts tab is shown in the sidebar.

I can verify that the filter works correctly on Mac and iPhone both using AdGuard and Safari; so the setup is not at fault. I have tested this on two separate iPads; both running iOS 16.1 and the filter in ineffective on both; I also tried inputing the filter rules directly and linking my letsblockit filter url. So it seems like its consistent and limited to the version of YouTube being displayed on iPads (and possibly other tablets if anyone can test?)

### Additional notes

Im not sure what further information I can provide to help; but if there more I can add feel free to ask!

**Comment by xvello** [comment] 2022-11-14 13:00
Hello @Melonking906, thanks for opening this issue!

YouTube serves two different websites for desktop and mobile. I would not be surprised they serve a third website to tablets. In that case, it will require us to write a third set of rules.

I'm not sure I'll have the bandwidth to look into this in November, but we'll definitely look into add this. In the meantime, could you please:

- tell us what website you are directed to on a tablet, you can simply copy/paste the URL from your browser
- try out directly going to m.youtube.com, to test whether this could force the mobile layout, as a workaround

**Comment by xvello** [comment] 2022-11-14 13:01
Note to contributors: I developed the mobile version of the rules by using a "user agent switcher" extension on Firefox desktop, we should try spoofing the user agent as a tablet and check what markup we are served.

**Comment by Melonking906** [comment] 2022-11-14 13:58
I did a little more testing after your message and the story gets weirder!

The iPad url is simply https://www.youtube.com and it looks the same as the desktop site.

If you tap the aA symbol in the Safari address bar and press "Request Mobile Site" it will switch to m.youtube.com; on the mobile site, as far as I can tell switching between mobile and desktop modes; shorts are not blocked on both. However the mobile version is different to the iPhone mobile version; its older and clunkier looking (it also does not appear to support shorts although they do show up in your feed as regular videos). I tried switching on and off filters and clearing browser data but it had no noticeable affect.

I also tried looking at the site in iPad mode on Firefox and Safari on desktop; the filter appears to be working fine on both.. so the only conclusion I can come to is that its something device related. With that in mind Im gonna send on this thread to AdGuard support in case they can shed more light on it.

**Comment by Melonking906** [comment] 2022-11-17 12:37
Following up; I received a reply from AdGuard that confirms your theory and explains a few of the other quirks.

`The AdGuard filter maintainers don't think it might be an AdGuard bug; youtube.com on iPad has a different layout, so it might not contain elements triggering rules from the filter.
 
Moreover, the Safari Content Blocker technology does not support the has:() modifier and the regexp support is quite limited, too. When switching user agents to iPad or iPhone on a Mac, websites are still filtered by the standalone AdGuard app, not by [Safari Content Blockers](https://developer.apple.com/documentation/safariservices/creating_a_content_blocker).`

So it sounds like the issue might be inherently related to iPad limitations. Im not sure if there is a work-around for the has:() issue, it would be great if there was; although this seems like an edge case, so I can see why it might not be a priority!

**Comment by krystian3w** [comment] 2022-12-08 11:18
Safari 15.4 added support native simple `:has()` - https://caniuse.com/css-has. Unlock this for latest AdGuard Content Blocker "Extension" maybe is undesirable.


Using ExtendedCSS syntax may need enable advanced filtering via AdGuard WebExtension: https://adguard.com/en/blog/adguard-4-3-for-ios.html*

On my side, the part functions of WebExtension does not want to work even on the iPhone SE 2022.

Both scenarios need supported hardware*:

iPad | iPad mini | iPad Pro
-- | -- | --
Air 2<br>Air 3<br>Air 4<br>Air 5<br>5. gen<br>6. gen<br>7. gen<br>8. gen<br>9. gen | Mini 4<br>Mini 5<br>Mini 6 | Pro 12,9″<br>Pro 12,9″ (2. gen)<br>Pro 12,9″ (3. gen)<br>Pro 12,9″ (4. gen)<br>Pro 12,9″ (5. gen)<br>Pro 9,7″<br>Pro 10,5″<br>Pro 11″<br>Pro 11″ (2. gen)<br>Pro 11″ (3. gen)


> \* - here you need to verify that it works in the free version App with the **iPad**OS or even after paid licence.

Maybe a little help another WebExtension:

https://apps.apple.com/us/app/web-inspector/id1584825745?platform=ipad

To see html code - maybe don't have nothing special to hide shorts.

**Comment by xvello** [comment] 2023-01-02 18:58
I currently do not have the hardware nor the time to look into this issue, but I'm tagging it as `help wanted`, because I'd be happy to review a contribution implementing it.

For now, uBlockOrigin is the target content blocker, and support for other blockers is on a best-effort basis.

**Comment by xvello** [comment] 2023-01-23 11:30
Most of our rules could be written with `:upward()` selectors instead of  `:has()`, which would help with performance too.
https://github.com/letsblockit/letsblockit/pull/335 rewrites the rules of the youtube-shorts template, but this probably won't be enough for ipads.

From my testing by switching user-agents, it looks like youtube still serves an old layout to tablets (both android & ipad), without the shorts logo on the thumbnail. Hopefully, they will rollout their new design to tablets soon, and we won't need to re-introduce the duration-based rules that we removed in https://github.com/letsblockit/letsblockit/pull/326

**Comment by xvello** [comment] 2023-10-15 10:09
I think it's time to re-open the conversation around AdGuard support, we're discussing it in https://github.com/orgs/letsblockit/discussions/577

**Comment by Alex-302** [comment] 2023-11-07 10:44
> For some reason the shorts filter in entirely ineffective on iPads looking at YouTube via Safari with the AdGuard app. Shorts show up in subscriptions and the shorts tab is shown in the sidebar.

Hi. Which rules did you try?

**Comment by xvello** [comment] 2023-11-07 12:51
Hello @Alex-302, there's two facets to this issue:

1. the rules we publish on https://letsblock.it/filters/youtube-shorts target both the desktop and mobile layouts, but don't currently support the third tablet layout that iPads (and Android tablets) are served. As none of the main contributors own a tablet, we have not prioritized that, but contributions are welcome

2. none of the core contributors to this project own an iOs device, so we are not clear on whether AG for Safari and AG for iOS support extended cosmetic filtering syntax or not. A public reference of their capabilities and whether additional setup (in the extension settings or by trusting the list) is needed would be very helpful for us to triage such compatibility issues.

**Comment by Alex-302** [comment] 2023-11-07 13:28
@xvello 

> 1. the rules we publish on https://letsblock.it/filters/youtube-shorts

Syntax is ok for `AdGuard for iOS/Safari`. But iOS does not support regexps well.
That rules work on my desktop, also in Safari/iOS this button is hidden

![image](https://github.com/letsblockit/letsblockit/assets/8361299/1e749591-c2b6-4967-991e-d86979e3f666)

I don't see Shorts section like on desktop with/without AdGuard.
Without a screenshot I don't understand what OP means.

**Comment by Melonking906** [comment] 2023-11-07 14:16
> I don't see Shorts section like on desktop with/without AdGuard. Without a screenshot I don't understand what OP means.

I'm unsure if there was a shorts section on desktop youtube at the time this was reported; however, I believe I was referring the shorts videos that show up within the home and subscriptions feeds. Not a dedicated shorts tab/section.

![CleanShot 2023-11-07 at 14 15 08@2x](https://github.com/letsblockit/letsblockit/assets/1700367/80dd2217-248b-47fe-af14-ff1eb3dd5671)
(Shorst as seen in the subscriptions feed when AdGuard is disabled)

**Comment by JohnyP36** [comment] 2023-11-07 14:28
The rule `##ytd-guide-renderer a.yt-simple-endpoint path[d^="M10 14.65v-5.3L15 12l-5 2.65zm7.77-4.33"]:upward(ytd-guide-entry-renderer)` hides the shorts shortcut in the sidebar of YouTube and can be found in the template. Also the same template blocks the sections on the homepage. (**All applied for desktop and mobile**)

**Comment by Nomes77** [comment] 2023-11-07 14:50
If I use the Responsive Design Modus in FireFox on Windows 10 and select `iPad iPadOS` 14.7.1`, I can't reproduce any problem with the Shorts template.

**Comment by xvello** [comment] 2023-11-10 11:10
Thanks all for your input!

- When that issue was opened (a year ago, time flies!), tablets were served a different layout than desktop and mobile. I just tested it, and now tablet user-agents are served the same version as mobile. When testing with https://add0n.com/useragent-switcher.html, I can confirm that the usual places where shorts are shown are properly targeted by our rules. *Note that the tablet layout could change again in the future without notice.*

- Proper targeting will require `AdGuard Advanced blocking` to be enabled though. Is that still [a premium-only feature](https://adguard.com/en/blog/adguard-4-3-for-ios.html)?

@Melonking906 unless you write otherwise, I'll close this issue now. 

@Alex-302 thanks for helping us on this issue. If we were to receive more reports of Safari-specific issues, is there a non-disruptive way for us to ping your team?

**Comment by Alex-302** [comment] 2023-11-10 13:48
> Proper targeting will require AdGuard Advanced blocking to be enabled though. Is that still [a premium-only feature](https://adguard.com/en/blog/adguard-4-3-for-ios.html)?

Yes, only on iOS.

> If we were to receive more reports of Safari-specific issues, is there a non-disruptive way for us to ping your team?

Sure:)

**Closed** 2023-11-11 17:41 UTC
Labels: help wanted, filter-data
