### ISSUE TITLE
Google's "Remove everything but simple results in the text search" filter breaks google news and shopping

### ISSUE THREAD

**Issue by pitsi** [letsblockit/letsblockit#219] opened 2022-07-14 17:36 UTC
### Describe the bug

On a chromium based browser, add the last filter about google's search, i.e. this one, which is described as "Remove everything but simple results in the text search"

`!google.*###rso > :not(div.g):not(:has(:scope>div.g))`

Then search anything on google and click the news tab from the top. You will notice that it returns no results, which means that every result is blocked from that filter.

On the other hand, the issue does not happen on firefox!

Tested on chromium and chrome 103 on windows and on brave 1.41 and chromium 103 on linux.

### Your browser and device

Windows chromium 103, windows chrome 103, linux chromium 103, linux brave 1.41, all desktop browsers

### Reproduction steps

```bash
1. Add all the filters available for google and especially the last one.
2. Go to google and search for something.
3. Click the news tab to see any news related to whatever you searched for.
```

### Expected behavior

The browser should display the news results for the searched word, like it does on firefox (102 as of today).
Also, disabling the forementioned filter instantly fixes the issue on chromium based browsers.

### Additional notes

None I can think of right now.

**Comment by pitsi** [comment] 2022-07-15 09:40
I also noticed that this filter removes regular results from search which are "moved" to the second page.
For instance, I searched yesterday for "asrock deskmeet" and all I got was only 3 or 4 results in the first page
Those 3 results on the first page were 2 reviews and a shop listing :P

**Comment by xvello** [comment] 2022-07-15 19:32
Indeed. I'll definitely remove that filter, it's too blunt of an instrument.

I think I'll replace with the following rules, that match most "rich content" results. If you have some time, I'd love for you to try and confirm that they don't break other pages (always good to have more eyes on an issue):

> google.*###rso > div:has(g-more-link)
> google.*###rso > div:has(g-scrolling-carousel)

FYI, you can add a `:style` instruction to rules to apply a style instead of hiding elements that match a rule:

> google.*###rso > div:has(g-more-link):style(border: 2px dashed red !important)
> google.*###rso > div:has(g-scrolling-carousel):style(border: 2px dashed red !important)

**Comment by pitsi** [comment] 2022-07-17 06:46
I am really sorry that I can not participate in the testing of the above, but I had a minor injury on my arm yesterday and it will probably keep me away for some days.

**Comment by xvello** [comment] 2022-07-17 09:31
Hello @pitsi, sorry to read that. hope you get better soon!

I iterated over the filters I posted above, and ended up with the ones in https://github.com/letsblockit/letsblockit/pull/223, that's the final version that I'll test extensively then release this afternoon.

As per the "asrock deskmeet", the issue is that the "All but simple results" filter also hid  grouped results like this, because that layout was added after I released the filter. Fixed in the proposed filters in https://github.com/letsblockit/letsblockit/pull/223 !

![image](https://user-images.githubusercontent.com/6241083/179392325-c7fdd767-59d5-4b12-bb55-415285cf9d3a.png)

**Comment by pitsi** [comment] 2022-07-19 09:14
I finally got the red dashes after a search! What am I doing next? Can I add the new filters the site provides?

![2022-07-19-121104_1280x1024_scrot](https://user-images.githubusercontent.com/5880037/179714175-080113ae-2f97-4059-8f43-15bb38384e02.png)

p.s. Sorry for the late reply :(

**Comment by xvello** [comment] 2022-07-19 10:19
Heya @pitsi, thanks for the update! As described in [the changelog](https://github.com/letsblockit/letsblockit/releases/tag/v0.20.0), the new template is deployed.
You just need to go to https://letsblock.it/filters/google-search-cleanup, login and make sure the first option is enabled. Then [refresh your list](https://letsblock.it/help/refresh-list) and enjoy!

**Comment by pitsi** [comment] 2022-09-30 16:08
I have the same issue again. I disabled the same line on the filters, but nothing thanges.
I deleted all lines and re-added them from the page, but still nothing. Any ideas?

Brave 1.44, based on chromium 106 and ubo 1.44.4.

**Comment by xvello** [comment] 2022-10-02 09:21
Hello @pitsi, sorry to read that. Could you please clarify what is happening?

- What pages are affected? Please provide links
- Is the rule blocking too much? Please use [uBO's DOM inspector](https://github.com/gorhill/uBlock/wiki/DOM-inspector) to identify what element is matched, by what rule. Please provide screenshots like in the linked wiki page
- Is the rule not blocking anymore? In https://github.com/letsblockit/letsblockit/pull/241 we updated these rules to only work on `www.google.*` subdomains to avoid side-effects, are the pages on a different subdomain?

**Comment by pitsi** [comment] 2022-10-03 11:23
It does not happen all the time or with all the searches, so please give me some days to investigate it more and I will report back. For instance, yesterday I searched for a greek journalist who died and the page was empty. Today I searched for the linux kernel and it returned results as usual. Truth is I do not use google's news feature that often, but the searches I make are about recent news.

Thank you :)

**Comment by xvello** [comment] 2022-10-03 11:47
Thanks. It does look pretty similar to https://github.com/letsblockit/letsblockit/issues/170, where the issue was a new layout for results about cultural works (books, movies...). Probably a new dedicated layout for some other result type? URLs and DOM inspector screenshots would be helpful, when you find a page with the issue.

**Comment by pitsi** [comment] 2022-10-03 15:16
Is this (image) enough info from the logger? I am sorry that the search term is in greek. Searches in english work fine as it seems. The search url, without all the junk that google adds, can be limited to this
`https://www.google.com/search?q=%CF%87%CE%B1%CF%84%CE%B6%CE%B7%CF%86%CF%89%CF%84%CE%B9%CE%BF%CF%85&source=lnms&tbm=nws`

![2022-10-03-181307_934x399_scrot](https://user-images.githubusercontent.com/5880037/193613631-55606b6f-587b-43e7-9768-b64ed7c319a4.png)

**Comment by xvello** [comment] 2022-10-04 20:37
Thanks for the URL. I could not reproduce on that page, but it triggers for me on [this search](https://www.google.com/search?q=test&tbm=nws&ved=2ahUKEwiu3ILjycT6AhXGhc4BHTi0CsgQ_AUoAXoECAIQAw&dpr=1.2).

I think I have one idea to make the filter less greedy so that it does not filter out these new layouts. We will still get some junk in these pages, but that will be for another time.

**Comment by xvello** [comment] 2022-10-04 21:00
@pitsi I will test out the following variation of the rules:

```adblock
www.google.*###rcnt > div:first-of-type:not([id]) > div:has(g-more-link,g-scrolling-carousel):style(border: 2px dashed red !important)
www.google.*###rso > div:not(:only-child):has(g-more-link,g-section-with-header):style(border: 2px dashed red !important)
www.google.*###rso > div:not(:only-child):has(div[role="heading"]+g-scrolling-carousel):style(border: 2px dashed red !important)
www.google.*###kp-wp-tab-overview > div:has(g-more-link,g-section-with-header,#media_result_group):style(border: 2px dashed red !important)
www.google.*###rso > div:not(:only-child):has(div.related-question-pair):style(border: 2px dashed red !important)
www.google.*###kp-wp-tab-overview > div:has(div.related-question-pair):style(border: 2px dashed red !important)
www.google.*###botstuff #bres:style(border: 2px dashed red !important)
www.google.*###rso div.g div[jscontroller][id^="eob_"]:style(border: 2px dashed red !important)
www.google.*##div.isv-r[data-rfg]:style(border: 2px dashed red !important)
```

Lines 2, 3 and 5 are changed to only match on the text results' standard layout. Instead of looking for the presence of a `#kp-wp-tab-overview` element (the new layout for cultural works), I am checking that the `#rso` item has several `div` children. This should effectively neuter these rules on the alternative news layout that we are randomly served.

If you have some time, I'd appreciate if you could disable the filter in letsblock.it and test out this version for a couple of days. As I fully transitionned to kagi.com, I rarely go to google anymore.

**Comment by pitsi** [comment] 2022-10-05 16:15
Now I can't reproduce it, neither with the greek word, nor with linux! And with any other word as it seems. although I tried a bunch of random stuff. 
Shall I add the new filters or wait?

**Comment by xvello** [comment] 2022-10-06 19:34
>Now I can't reproduce it, neither with the greek word, nor with linux! And with any other word as it seems. although I tried a bunch of random stuff.

Welcome to my world :sweat: 

>Shall I add the new filters or wait?

It would be very helpful if you could run these new filters before I release them this weekend. Ideally the version I posted with the `:style(border: 2px dashed red !important)` ending so that you can look for false-positives, but if that's too annoying you can remove that suffix and use them in a hiding fashion.

I'll do a last pass for false-positives this weekend, then release them unless someone shouts ^^

**Comment by pitsi** [comment] 2022-10-07 06:00
Well... I see the red dashes around or under some results, which means that (all?) the rules above work.
I also see results on news, but the last result of each page is always underlined, regardless of the search term.

I also have a issue with google's gdrp consent popup on news, which does not go away no matter what I select, but this is probably another story because it happens regardless if I have your filters on or off.

**Comment by xvello** [comment] 2022-10-07 16:47
The red underline is caused by the `Hide the "People also search for" popup shown when returning to results` option, the element is folded by defaut, and only expanded if you come back to the search results after clicking a link. You can safely ignore these.

None of the rules here should mess with the GDRP popup indeed, I'm assuming that's a rule from an annoyances list misbehaving?

**Comment by pitsi** [comment] 2022-10-08 05:55
About the gdrp popup. I have the "I don't care about cookies" list and ublock's one for annoyances, but none of them seems to be filtering out google's popup. Everytime I open a private window to search something, I have to press "I do not accept". The window goes away on regular google, but does not go away when I open it straight under news, e,g, by opening one of the urls above.

About the underlines/dashes. This is what I see on a "casual" search. Almost everything is inside a red box on page 1 of the results, while page 2 does not seem to have such an issue. There are times that the first page does have 2-3 results without that red box.

![2022-10-08-084006_1280x1024_scrot](https://user-images.githubusercontent.com/5880037/194691368-985ee394-bf1c-4f22-8528-4112bf3d33e3.png)

**Comment by xvello** [comment] 2022-10-08 12:00
Thanks for catching that one! It would indeed hide everything but the "smart" result that the top. Looking into this

**Comment by xvello** [comment] 2022-10-09 16:26
Heya, sorry for the delay. I think the following change to the rules should be enough for now. I think it's not the best for performance, but we can revisit later on. What I'm doing is using `#rso:has(> div:nth-of-type(6))` to select for the "typical" layout, with at least 6 result divs under `#rso`.

```adblock
www.google.*###rcnt > div:first-of-type:not([id]) > div:has(g-more-link,g-scrolling-carousel):style(border: 2px dashed red !important)
www.google.*###rso:has(> div:nth-of-type(6)) > div:has(g-more-link,g-section-with-header):style(border: 2px dashed red !important)
www.google.*###rso:has(> div:nth-of-type(6)) > div:has(div[role="heading"]+g-scrolling-carousel):style(border: 2px dashed red !important)
www.google.*###kp-wp-tab-overview > div:has(g-more-link,g-section-with-header,#media_result_group):style(border: 2px dashed red !important)
www.google.*###rso:has(> div:nth-of-type(6)) > div:has(div.related-question-pair):style(border: 2px dashed red !important)
www.google.*###kp-wp-tab-overview > div:has(div.related-question-pair):style(border: 2px dashed red !important)
www.google.*###botstuff #bres:style(border: 2px dashed red !important)
www.google.*###rso div.g div[jscontroller][id^="eob_"]:style(border: 2px dashed red !important)
www.google.*##div.isv-r[data-rfg]:style(border: 2px dashed red !important)
```

**Comment by pitsi** [comment] 2022-10-09 17:14
What should I notice now? News seem to work fine and I am getting no red squares.
Results from facebook/instagram/social media are underlined in red, along with related searches, the "other users searched for" boxes, links to apple, microsoft and play stores, links to wikipedia etc. Is all that ok?

**Closed** 2022-10-10 18:09 UTC
Labels: bug, filter-data
